#!/usr/bin/env sh

bold() { echo "$(tput bold)$*$(tput sgr0)"; }
show() { bold "→ $*" >&2; "$@"; }

git diff --cached --quiet --exit-code && bold "Nothing to lint!" && exit 0

EXIT_STATUS=0

show git stash --keep-index --include-untracked

show poetry run -- isort . || EXIT_STATUS=$?
show poetry run -- black . || EXIT_STATUS=$?
show poetry run -- mypy --namespace-packages poetry_relax || EXIT_STATUS=$?

git stash pop --quiet
exit $EXIT_STATUS
